name: manage-azure-policy-4a417976
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Management_ports_of_virtual_machines_should_be_protected_with_just-in-time_network_access_control_b0f33259-77d7-4c9e-aac6-3aabcfae693c/**'
#      - .github/workflows/manage-azure-policy-4a417976.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_4a417976}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Management_ports_of_virtual_machines_should_be_protected_with_just-in-time_network_access_control_b0f33259-77d7-4c9e-aac6-3aabcfae693c/**
